# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181211_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10)),
                ('productimg', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('marketprice', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
