# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='productid',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
